name: snap-store
version: git
version-script: |
  echo next.$(date --utc +%Y%m%d).$(git rev-parse HEAD | cut -c -7)
summary: Snap Store
description: |
  Snap Store allows you to find and install new applications and remove
  existing installed applications.

  Snap Store showcases featured and popular applications with useful
  descriptions and multiple screenshots per application.
  Applications can be found either through browsing the list of categories
  or by searching.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  snap-store:
    interface: dbus
    bus: session
    name: io.snapcraft.Store

apps:
  snap-store:
    command: bin/desktop-launch ${SNAP}/usr/bin/snap-store
    desktop: usr/share/applications/io.snapcraft.Store.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - snapd-control
      - unity7
      - wayland
      - system-observe
      - upower-observe
  ubuntu-store:
    command: bin/desktop-launch ${SNAP}/usr/bin/snap-store
    desktop: usr/share/applications/com.ubuntu.Store.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - snapd-control
      - unity7
      - wayland
      - system-observe
      - upower-observe

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
  snapd-glib:
    after: [desktop-gnome-platform]
    source: https://github.com/snapcore/snapd-glib
    source-type: git
    plugin: autotools
    configflags: [--prefix=/usr, --disable-glibtest, --disable-introspection, --disable-vala]
    organize:
      snap/snap-store/current/usr: usr
    build-packages:
      - gtk-doc-tools
      - libglib2.0-dev
      - libjson-glib-dev
      - libpolkit-gobject-1-dev
      - libsoup2.4-dev
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/share/pkgconfig
  libxmlb:
    after: [desktop-gnome-platform]
    source: https://github.com/hughsie/libxmlb.git
    source-type: git
    plugin: meson
    meson-version: "0.50.0"
    meson-parameters:
      - --prefix=/usr
      - -Dintrospection=false
    organize:
      snap/snap-store/current/usr: usr
    build-packages:
      - libglib2.0-dev
      - libstemmer-dev
      - uuid-dev
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/share/pkgconfig
  snap-store:
    after: [snapd-glib]
    source: .
    plugin: meson
    meson-version: "0.50.0"
    meson-parameters:
      - --prefix=/snap/snap-store/current/usr
    organize:
      snap/snap-store/current/usr: usr
    build-packages:
      - intltool
      - libglib2.0-bin
      - libglib2.0-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - pkg-config
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/share/pkgconfig
      - -usr/lib/*/gdk-pixbuf-2.0
      - -usr/lib/*/gio
      - -usr/lib/*/gtk-3.0
  magic:
    after: [snap-store]
    plugin: nil
    stage-packages:
      - libglib2.0-0
      - libglib2.0-bin
      - shared-mime-info
    override-prime: |
      set -eux
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
